[build]
  publish = "."

[functions]
  directory = "netlify/functions"

# 예약 페이지 슬러그
[[redirects]]
  from = "/1551-9708"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/1551-9708/"
  to = "/index.html"
  status = 200